# Generated by Django 4.0.3 on 2022-04-02 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_post_description_blog_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
